spring:
  application:
    name: lotusplus

  datasource:
    url: jdbc:postgresql://localhost:5432/lotusplus
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 3000ms

  cache:
    type: redis

redisson:
  address: redis://localhost:6379

server:
  port: 8080

checkin:
  morning:
    start: "00:00"
    end: "18:00"
  evening:
    start: "19:00"
    end: "21:00"

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE