spring:
  application:
    name: lotusplus

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      timeout: 3000ms

  cache:
    type: redis

redisson:
  address: redis://${SPRING_DATA_REDIS_HOST}:${SPRING_DATA_REDIS_PORT}

server:
  port: 8080

checkin:
  morning:
    start: "09:00"
    end: "11:00"
  evening:
    start: "19:00"
    end: "21:00"

logging:
  level:
    com.example.lotusplus.common.lock: DEBUG
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: TRACE